// @generated by protoc-gen-es v2.2.4 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file proto/greeter.proto (package proto, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file proto/greeter.proto.
 */
export declare const file_proto_greeter: GenFile;

/**
 * @generated from message proto.HelloRequest
 */
export declare type HelloRequest = Message<"proto.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated google.protobuf.Any details = 2;
   */
  details: Any[];
};

/**
 * Describes the message proto.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export declare const HelloRequestSchema: GenMessage<HelloRequest>;

/**
 * @generated from message proto.HelloReply
 */
export declare type HelloReply = Message<"proto.HelloReply"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message proto.HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export declare const HelloReplySchema: GenMessage<HelloReply>;

/**
 * @generated from service proto.Greeter
 */
export declare const Greeter: GenService<{
  /**
   * @generated from rpc proto.Greeter.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloReplySchema;
  };
}>;
