# See comment in examples/BUILD.bazel
# java_binary(
#     name = "java",
#     srcs = ["Main.java"],
#     main_class = "Main",
#     deps = [
#         "//:foo_java_proto",
#         "@protobuf-java//jar",
#     ],
# )
