name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@646899086d7aaee8e532540480f3e91e00596234 # Dec 11 2024
    with:
      folders: '[".", "e2e/smoke", "examples"]'
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false},
          {"folder": "examples", "bzlmodEnabled": false},
          {"bazelversion": "8.0.0", "bzlmodEnabled": false},
          {"bazelversion": "7.4.1", "folder": ".", "os": "ubuntu-latest"},
          {"bazelversion": "7.4.1", "folder": "examples", "os": "ubuntu-latest"}
        ]
