name: Mirror Releases
on:
  # Trigger manually in the UI
  workflow_dispatch:
  # Trigger daily at 06:10 UTC
  # Note, the create-pull-request action only sends a PR if there's a code change,
  # so a no-op execution of the mirror_protoc_releases script on most days will
  # not create a pull request.
  schedule:
    - cron: "10 6 * * *"

# Allow the pull request we create to run checks
permissions:
  contents: write
  actions: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./protoc/private/mirror_protoc_release.sh
          npx @bazel/buildifier protoc/private/versions.bzl
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: mirror protoc release"
